version: '3.7'

services:
  web:
    image: node:11-alpine
    command: yarn docker-dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mariadb
    volumes:
      - ../be-member-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=be_member
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 81:80
